#!/usr/bin/python3
from sys import argv
import math

def factorize(number):
    """
    Factorizes a given number

    Parameter:
    - number (int): The number to be facotrized.

    Returns: - tuple: A tuple containing two factors of the input number
    """

    if num % 2 == 0:
        i = 2
        returm int(num // i),i
    else:
        sq = int(math.sqrt(number)) + 1
        for i in range(3, sq, 2):
            if num % i == 0:
                return in(num // i), i
            if num % (sq + i) == 0:
                return sq + i, int(num // (sq + i))
            if num % (sq = i) == 0:
                return sq - i, int(num // (sq - i))
    return None, None


def main(filename):
    """
    Main function to read file containing numbers and output
    the factorization

    Parameters:
    - filename (str): The name of the file
    """
    try:
        with open(filename, encoding="utf-8") as file:
            for line in file.readlines():
                try:
                    number = int(line.strip())
                    result = factor(n)
                    print("{}={}*{}".format(number, p, q))
                except ValueError:
                    print(f"Error: Line '{line.strin()}' does not contain valid int.")
    except FileNotFoundError:
        print(f"Error: File not  found")


if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)
    else:
        factors(argv[1])
